- Assets/Masuda.meta
- Assets/Masuda/Scene_M.unity
- Assets/Masuda/Scene_M.unity.meta
- Assets/Masuda/Script_M.meta
- Assets/Masuda/Script_M/CameraPos_M.cs
- Assets/Masuda/Script_M/CameraPos_M.cs.meta
- Assets/Masuda/Script_M/ChangeChara_M.cs
- Assets/Masuda/Script_M/ChangeChara_M.cs.meta
- Assets/Masuda/Script_M/CharaMove_M.cs
- Assets/Masuda/Script_M/CharaMove_M.cs.meta
- Assets/Masuda/Script_M/ChickenKick_M.cs
- Assets/Masuda/Script_M/ChickenKick_M.cs.meta
- Assets/Masuda/Script_M/Cutter_M.cs
- Assets/Masuda/Script_M/Cutter_M.cs.meta
- Assets/Masuda/Script_M/Enemy2_M.cs
- Assets/Masuda/Script_M/Enemy2_M.cs.meta
- Assets/Masuda/Script_M/Transition_M.cs
- Assets/Masuda/Script_M/Transition_M.cs.meta
> no message

- Assets/Masuda.meta
- Assets/Masuda/GameScene_M.unity
- Assets/Masuda/GameScene_M.unity.meta
- Assets/Masuda/Materials_M.meta
- Assets/Masuda/Materials_M/Douro.mat
- Assets/Masuda/Materials_M/Douro.mat.meta
- Assets/Masuda/Materials_M/Niwa.mat
- Assets/Masuda/Materials_M/Niwa.mat.meta
- Assets/Masuda/Script_M.meta
- Assets/NewProto/Masuda.meta
- Assets/NewProto/Masuda/Scene_M.unity.meta
- Assets/NewProto/Masuda/Script_M.meta
- Assets/NewProto/SASAKI/Scripts/FoodMaker_R.cs.meta
- ProjectSettings/QualitySettings.asset
> スコアの金額化とstage1のコード入れ

- Assets/Masuda/GameStart_M/GameStart_M.unity
- Assets/Masuda/Script_M/GameStart_M.cs
- Assets/NewProto/SASAKI/Scripts/Parameters_R.cs
- ProjectSettings/EditorBuildSettings.asset
> hpバーの増量とタイトルからstage1への移行

- Assets/Abe/stage1.unity
> Set property

- Assets/NewProto/SASAKI/Prefabs/Cutter.prefab
- Assets/NewProto/SASAKI/Prefabs/Food.prefab
- Assets/NewProto/SASAKI/Scene_S.unity
- Assets/NewProto/SASAKI/Scripts/CharaMoveRigid_R.cs
- Assets/NewProto/SASAKI/Scripts/CutterMove1_R.cs
- Assets/NewProto/SASAKI/Scripts/CutterMoveFA_R.cs
- Assets/NewProto/SASAKI/Scripts/Cutter_R.cs
疲れました
Raycast君ってどうしてこうも使いづらいんですかね…
> カッター&接地判定修正した～

- Assets/Masuda/GameStart_M/GameStart_M.unity
- Assets/NewProto/SASAKI/Scripts/Parameters_R.cs
- Assets/NewProto/SASAKI/Scripts/Result_R.cs
リザルトでスコアがちゃんと反映されるようにしたのとHPが進化に合わせて変わるようにした（たぶん）。それとリトライでRを押してからロードで待ってるときにちゃんと押せてるか分かりづらい気がしたから、黒い画面がでるようにした。
> リザルトとHPの修正とロード画面的なものの追加

- Assets/NewProto/SASAKI/Scripts/Parameters_R.cs
エサ10個で1秒時間が伸びて、敵に攻撃されると10秒時間が減るようにしました。
HPゲージはまだ消すかどうか未定なので隠しました。
> HP系を時間変化に変更

- Assets/NewProto/Yamamoto/Material/HitBoxMaterial.mat
> alpha_ver0.1

- Assets/NewProto/Yamamoto/Scripts/ClerkMove.cs
- Assets/NewProto/Yamamoto/Scripts/PoliceMove.cs
- Assets/NewProto/Yamamoto/Scripts/TankMove_Y.cs
なんでUpdate()でGetComponentしてるんですかね…
> エネミーのHP連携処理を変更

- Assets/Examples.meta
- Assets/NewProto/Yamamoto/Object/GameAI_Y.prefab
- Assets/NewProto/Yamamoto/Object/WayPoint.prefab
- Assets/NewProto/Yamamoto/Scripts/SpawnerWaypoint_Y.cs
- Assets/NewProto/Yamamoto/Scripts/WayPointGraph_Y.cs
- Assets/NewProto/Yamamoto/Scripts/WayPointGraph_Y.cs.meta
- Assets/NewProto/Yamamoto/Scripts/WayPoint_Y.cs
- Assets/NewProto/Yamamoto/Scripts/WayPoint_Y.cs.meta
> 市民の経路探索アルゴリズム変更

- Assets/Abe/Building/template/Format/type1.prefab
- Assets/Abe/Prefab/Tree.prefab
- Assets/NewProto/Yamamoto/ChechScene_Y.unity
- Assets/NewProto/Yamamoto/Scripts/Etcetra/Test_ADX.cs
- Assets/NewProto/Yamamoto/Scripts/Etcetra/Test_ADX.cs.meta
- Assets/NewProto/Yamamoto/Scripts/Object/ObjectBreak_Y.cs
- Assets/NewProto/Yamamoto/Scripts/Object/ObjectStateManagement_Y.cs
- Assets/NewProto/Yamamoto/Test_ADX.unity
- Assets/NewProto/Yamamoto/Test_ADX.unity.meta
- Assets/Nishiki/Building/template/bill45.prefab
> ADXの音ならない問題対処

- Assets/Editor/CriWare/CriWareBuildPreprocessorPrefs.asset
- Assets/Editor/CriWare/CriWareBuildPreprocessorPrefs.asset.meta
Stage1の起動速度が明らかに早くなった気がするんですけど…
ついでに心なしかゲーム自体も軽くなった気がする…
> ステージ上の非アクティブになっている建物を消去

- Assets/GameScenes/GameStart_M.unity
- Assets/Masuda/Ingredients/blackWhite.png
- Assets/Masuda/Ingredients/blackWhite.png.meta
- Assets/Masuda/Ingredients/woodenBoardTrim.png
- Assets/Masuda/Ingredients/woodenBoardTrim.png.meta
- Assets/Masuda/MissionMove.anim
- Assets/Masuda/Script_M/ButtonRange_M.cs
- Assets/Masuda/Script_M/ButtonRange_M.cs.meta
- Assets/NewProto/SASAKI/Scripts/Parameters_R.cs
> スタート画面のボタンの設定とミッションの表示スピードの微調整とparameter_rのちょっと変更

- Assets/GameScenes/GameStart_M.unity
- Assets/Masuda/Mouse.controller
- Assets/Masuda/Mouse.controller.meta
- Assets/Masuda/MouseChange.anim
- Assets/Masuda/StoryCS_M/MouseAnimator_M.cs
- Assets/Masuda/StoryCS_M/MouseAnimator_M.cs.meta
- Assets/Nishiki/animations/commenteron.anim
> 店を破壊させるようにマウスのUIを設置

- Assets/ADX/ADX_SoundPlay01.cs
- Assets/GameScenes/GameStart_M.unity
- Assets/Masuda/Script_M/Option/Audio_M.cs
- Assets/NewProto/Yamamoto/ChechScene_Y.unity
- Assets/NewProto/Yamamoto/Scripts/Etcetra/SoundVolumeController.cs
- Assets/NewProto/Yamamoto/Scripts/Etcetra/SoundVolumeController.cs.meta
- Assets/NewProto/Yamamoto/Scripts/Object/DestoryShop_Y.cs
- Assets/NewProto/Yamamoto/Scripts/Object/DestoryShop_Y.cs.meta
- Assets/NewProto/Yamamoto/Scripts/Object/ObjectStateManagement_Y.cs
> ショップを最初に破壊するように変更

- Assets/Masuda/StoryCS_M/Cicleback_M.cs
- Assets/NewProto/SASAKI/Scripts/Parameters_R.cs
> ニワトリのゲージの調整

- Assets/ADX/Script/ADX_Ray_Rev.cs
- Assets/Users/Suda/Material/Ground.meta
- Assets/Users/Suda/Material/Ground/Tile.png
- Assets/Users/Suda/Material/Ground/Tile.png.meta
- Assets/Users/Suda/Material/Ground/TileRotate.png
- Assets/Users/Suda/Material/Ground/TileRotate.png.meta
- Assets/Users/Suda/Material/Ground/alleyTile.png
- Assets/Users/Suda/Material/Ground/alleyTile.png.meta
- Assets/Users/Yamamoto/Scripts/Etcetra/MiniMap_Y.cs
- Assets/Users/Yamamoto/Scripts/Etcetra/MiniMap_Y.cs.meta
- Assets/Users/Yamamoto/Scripts/Object/ObjectBreak_Y.cs
- Assets/Users/Yamamoto/Scripts/Object/ObjectStateManagement_Y.cs
> 超簡易MiniMap実装とCompliエラー対処

- Assets/GameScenes/prologue01.unity
- Assets/GameScenes/prologue02.unity
- Assets/Masuda.meta
- Assets/Masuda/StoryCS_M.meta
- Assets/Users/Masuda/Material/Shibu.mat
- Assets/Users/Masuda/Material/Shibu.mat.meta
- Assets/Users/Masuda/Script_M/TitleBack_M.cs
- Assets/Users/Masuda/Script_M/TitleBack_M.cs.meta
- Assets/Users/Masuda/StoryCS_M/SkipIcon_M.cs
- Assets/Users/Masuda/StoryCS_M/SkipIcon_M.cs.meta
- Assets/Users/Masuda/StoryCS_M/Stage1_M/Stage1_Mission_M.cs
- Assets/Users/Yamamoto/Scripts/Object/ObjectStateManagement_Y.cs
> ミッション用ヒント、木のカウント、プロローグのスキップ機能

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/Users/Masuda/Script_M/TitleBack_M.cs
- Assets/Users/Masuda/StoryCS_M/Mission2_M.cs
- Assets/Users/Masuda/StoryCS_M/Missions_M.cs
- Assets/Users/Masuda/StoryCS_M/NextStage_M.cs
- Assets/Users/Masuda/StoryCS_M/NextStage_M.cs.meta
- Assets/Users/Masuda/StoryCS_M/Stage1_M/Stage1Clear_M.cs
- Assets/Users/Yamamoto/Scripts/Object/ObjectStateManagement_Y.cs
- ProjectSettings/EditorBuildSettings.asset
ミッション2の直しとステージ1からステージ2への移動システム
> ミッション2の改正とステージ移動のシステム追加

- Assets/GameScenes/GameStart_M.unity
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Masuda/StoryCS_M/GameObj_Script/GasStandCount_M.cs
- Assets/Users/Masuda/StoryCS_M/GameObj_Script/GasTankCount_M.cs
- Assets/Users/Masuda/StoryCS_M/Mission2_M.cs
- Assets/Users/Masuda/StoryCS_M/Missions_M.cs
- Assets/Users/Masuda/StoryCS_M/Stage1_M/Stage1Clear_M.cs
- Assets/Users/Nishiki/Stage2/gasTank.prefab
> ゲームスタート画面の改良とステージ2のガスタンクの設定

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/GameScenes/prologue01.unity
- Assets/GameScenes/prologue02.unity
- Assets/Users/Abe/Eff_source/Big_Explosion_Eff/Gasstank_Eff.unitypackage.meta
- Assets/Users/Abe/Eff_source/New Folder.meta
- Assets/Users/Abe/Eff_source/Reality_exp_eff.meta
- Assets/Users/Masuda/Animetion/Mission.controller
- Assets/Users/Masuda/Animetion/Mission.controller.meta
- Assets/Users/Masuda/Animetion/MissionMove.anim
- Assets/Users/Masuda/StoryCS_M/GameObj_Script/GasTankCount_M.cs
- Assets/Users/Masuda/StoryCS_M/Mission1_M.cs
- Assets/Users/Masuda/StoryCS_M/Missions_M.cs
- Assets/Users/SASAKI/Scripts/Parameters_R.cs
- Assets/Users/Suda/Material/Props/egg.meta
> 新UIへの変更パート1

- Assets/Users/Abe/Eff_source/Big_Explosion_Eff/Gasstank_Eff.unitypackage.meta
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Abe/Eff_source/New Folder.meta
- Assets/Users/Abe/Eff_source/Reality_exp_eff.meta
- Assets/Users/Abe/SideWake_mat/Stage2_basemat/New Folder.meta
- Assets/Users/Yamamoto/Material/AirWallMaterial.physicMaterial
- Assets/Users/Yamamoto/Material/AirWallMaterial.physicMaterial.meta
- Assets/Users/Yamamoto/Material/TestIconMaterial.mat
- Assets/Users/Yamamoto/Material/TestIconMaterial.mat.meta
- Assets/Users/Yamamoto/Object/food_Y.prefab
- Assets/Users/Yamamoto/Scripts/Enemy/Enemy_Y.cs
- Assets/Users/Yamamoto/Scripts/MiniMap/TargetIcon_Y.cs
- Assets/Users/Yamamoto/Scripts/Object/ObjectStateManagement_Y.cs
- Assets/Users/Yamamoto/Scripts/Object/Stage3BossBuilding.cs
敵の姿勢調整修正
AirWallが突っかかってうざかったので物理Materialを貼り付けて修正
> Stage3のPhase管理スクリプト大体完成

- Assets/GameScenes/GameStart_M.unity
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Masuda/StoryCS_M/Mission2_M.cs
- Assets/Users/Masuda/StoryCS_M/Mission3_M.cs
- Assets/Users/Masuda/StoryCS_M/OpenScoreMode_M.cs
- Assets/Users/Masuda/StoryCS_M/OpenScoreMode_M.cs.meta
- Assets/Users/SASAKI/Scripts/Parameters_R.cs
> スコアアタック解放スクリプト(仮)

- Assets/GameScenes/prologue01.unity
- Assets/GameScenes/prologue02.unity
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
> ボタンアイコンの修正

- Assets/Users/Masuda/StoryCS_M/Mission3_M.cs
- Assets/Users/SASAKI/Scripts/Parameters_R.cs
> ミッション直しパート1

- Assets/GameScenes/GameStart_M.unity
- Assets/GameScenes/prologue01.unity
- Assets/GameScenes/prologue02.unity
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Masuda/StoryCS_M/MovieSkip_M.cs
- Assets/Users/Masuda/StoryCS_M/SkipIcon_M.cs
> タイトルとプロローグのUI改修

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/Users/Masuda/Animetion/MissionMove.anim
- Assets/Users/Masuda/StoryCS_M/ClickOff_M.cs
- Assets/Users/Masuda/StoryCS_M/Mission1_M.cs
- Assets/Users/SASAKI/Scripts/Parameters_R.cs
> UI変更（文字の変更、ゲーム画面UIの移動、ポップアップの手動オフ、ゲージの色変化）

- Assets/GameScenes/GameStart_M.unity
- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/GameScenes/prologue01.unity
- Assets/GameScenes/prologue02.unity
- Assets/Users/Masuda/Animetion/MissionMove.anim
- Assets/Users/Masuda/Script_M/PreScripts/BackPauseOption_M.cs
- Assets/Users/Masuda/Script_M/PreScripts/OptionP_M.cs
- Assets/Users/Masuda/StoryCS_M/Mission1_M.cs
- Assets/Users/Masuda/StoryCS_M/Missions_M.cs
> 文字の色をグレー寄りに、背景を濃い目に、タイトルでボタンの表示切替、アニメーションの手直しetc

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/Users/Masuda/StoryCS_M/Mission1_M.cs
- Assets/Users/Masuda/StoryCS_M/Mission2_M.cs
- Assets/Users/SASAKI/Scripts/Parameters_R.cs
> ゲージの色変換調整、ステージ1,2ミッションのテスト＆修正、ステージ3のクリア画面の修正

- Assets/GameScenes/GameStart_M.unity
- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Masuda/Script_M/GameScene_Language_M.cs
- Assets/Users/Masuda/Script_M/GameScene_Language_M.cs.meta
- Assets/Users/Masuda/Script_M/Option/ChangeLanguage.cs
- Assets/Users/Masuda/StoryCS_M/Mission1_M.cs
- Assets/Users/Masuda/StoryCS_M/Missions_M.cs
> 言語変更の設定(8割くらい済)

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/GameScenes/prologue01.unity
- Assets/GameScenes/prologue02.unity
- Assets/GameScenes/stage0.unity
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Masuda/Script_M/Prologue_Lan_M.cs
- Assets/Users/Masuda/Script_M/Prologue_Lan_M.cs.meta
- Assets/Users/Masuda/Script_M/Stage0_ButtonFlash_M.cs
- Assets/Users/Masuda/Script_M/Stage0_ButtonFlash_M.cs.meta
- Assets/Users/Masuda/Script_M/stage0Lan_M.cs
- Assets/Users/Masuda/Script_M/stage0Lan_M.cs.meta
- ProjectSettings/TagManager.asset
> 言語設定、ボタン点滅仮等

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/Users/Masuda/Ingredients/NewRes.meta
- Assets/Users/Masuda/Ingredients/NewRes/blast_mobileUI.png
- Assets/Users/Masuda/Ingredients/NewRes/blast_mobileUI.png.meta
- Assets/Users/Masuda/Ingredients/NewRes/cornIcon.png
- Assets/Users/Masuda/Ingredients/NewRes/cornIcon.png.meta
- Assets/Users/Masuda/Ingredients/NewRes/cutter_mobileUI.png
- Assets/Users/Masuda/Ingredients/NewRes/cutter_mobileUI.png.meta
- Assets/Users/Masuda/Ingredients/NewRes/gameOver_karaage.png
- Assets/Users/Masuda/Ingredients/NewRes/gameOver_karaage.png.meta
- Assets/Users/Masuda/Ingredients/NewRes/gameOver_karaageSmoke.png
- Assets/Users/Masuda/Ingredients/NewRes/gameOver_karaageSmoke.png.meta
- Assets/Users/Masuda/Ingredients/NewRes/hipstamp_mobileUI.png
- Assets/Users/Masuda/Ingredients/NewRes/hipstamp_mobileUI.png.meta
- Assets/Users/Masuda/Ingredients/NewRes/jump_mobileUI.png
- Assets/Users/Masuda/Ingredients/NewRes/jump_mobileUI.png.meta
- Assets/Users/Masuda/Ingredients/NewRes/kick_mobileUI.png
- Assets/Users/Masuda/Ingredients/NewRes/kick_mobileUI.png.meta
- Assets/Users/Masuda/Ingredients/NewRes/pause_mobileUI.png
- Assets/Users/Masuda/Ingredients/NewRes/pause_mobileUI.png.meta
- Assets/Users/Masuda/Script_M/GameScene_Language_M.cs
- Assets/Users/Masuda/StoryCS_M/New_GameOver_M.cs
- Assets/Users/Masuda/StoryCS_M/New_GameOver_M.cs.meta
- Assets/Users/SASAKI/Scripts/Result_R.cs
- Assets/Users/Yamamoto/Object/food_Y.prefab
> UI直し、ゲームオーバー設定など

- Assets/GameScenes/01-02mov.unity
- Assets/GameScenes/02-03mov.unity
- Assets/GameScenes/GameStart_M.unity
- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/GameScenes/ending.unity
- Assets/GameScenes/prologue01.unity
- Assets/GameScenes/prologue02.unity
- Assets/GameScenes/stage0.unity
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
> キャンバススケーラー設定の残り、進化パネルのボタン修正

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
> 固定ジョイスティック

- Assets/GameScenes/stage0.unity
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Masuda/Script_M/GameScene_Language_M.cs
- Assets/Users/SASAKI/Scripts/Parameters_R.cs
> 第4形態の体力ゲージ修正、ステージ0,1のインスペクターをいじった

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/Users/Masuda/Script_M/GameScene_Language_M.cs
- Assets/Users/Masuda/StoryCS_M/GameObj_Script/CarCount_M.cs
- save.json
> 翻訳直し、スクリプト直し

- Assets/ADX/Script/ADX_SoundPlay.cs
- Assets/GameScenes/01-02mov.unity
- Assets/GameScenes/02-03mov.unity
- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/GameScenes/ending.unity
- Assets/GameScenes/prologue01.unity
- Assets/GameScenes/prologue02.unity
- Assets/NewProto.meta
- Assets/Users/Masuda/StoryCS_M/Mission1_M.cs
- Assets/Users/SASAKI/Scripts/Gimmick/Car_R.cs
- Assets/Users/Suda/Material/chicken/form1/Materials.meta
- Assets/Users/Yamamoto/Object/Civil/StopCivil3 Variant.prefab
- Assets/Users/Yamamoto/Object/Civil/StopCivil4 Variant.prefab
- Assets/Users/Yamamoto/Object/Civil/StopCivil5 Variant.prefab
- Assets/Users/Yamamoto/Object/Civil/StopCivil6 Variant.prefab
- Assets/Users/Yamamoto/Object/GameAI_Y.prefab
- Assets/Users/Yamamoto/Scripts/Etcetra/BlastIntroduction_Y.cs
- Assets/Users/Yamamoto/Scripts/Etcetra/DebugSceneLoader.cs
- Assets/Users/Yamamoto/Scripts/Etcetra/DebugSceneLoader.cs.meta
- Assets/Users/Yamamoto/Scripts/Etcetra/SaveManager_Y.cs
- Assets/Users/Yamamoto/Scripts/Etcetra/TimeScaleFixer_Y.cs
- Assets/Users/Yamamoto/Scripts/Etcetra/TimeScaleFixer_Y.cs.meta
- Assets/Users/Yamamoto/Scripts/MiniMap/TargetIcon_Y.cs
TimeScaleが0fのままだったのが問題でした
その他停滞市民の挙動修正
> stage1経由すると01-02movがバグる問題対処

- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/Users/Masuda/Script_M/MobileOption_Howto.cs
- Assets/Users/Masuda/Script_M/MobileOption_Howto.cs.meta
> 紛失したスクリプトの修正

- Assets/GameScenes/GameStart_M.unity
- Assets/GameScenes/WorldAsset/WorldAssets.prefab
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Masuda/Script_M/DamagePanel_M.cs
- Assets/Users/Masuda/Script_M/DamagePanel_M.cs.meta
- Assets/Users/SASAKI/Scripts/Parameters_R.cs
- save.json
> 矢印直し、ダメージエフェクト、UI微調整

- Assets/GameScenes/01-02mov.unity
- Assets/Users/Abe/Eff_source/Evo_effect/Evo_Eff_Mat/Evo_Eff_Mat_001.mat
- Assets/Users/Masuda/Material/Shibu.mat
- Assets/Users/Nishiki/Stage2/gasStation.prefab
- Assets/Users/Suda/DividedPrefab/Pri_cells_45.prefab
- Assets/Users/Suda/DividedPrefab/Pri_cells_90.prefab
- Assets/Users/Suda/DividedPrefab/Pri_cells_F3.prefab
- Assets/Users/Suda/DividedPrefab/Pri_cells_F4.prefab
- Assets/Users/Suda/DividedPrefab/Pri_cells_F5.prefab
- Assets/Users/Suda/DividedPrefab/Pri_cells_F6.prefab
- Assets/Users/Suda/DividedPrefab/Pri_cells_gasStation.prefab
- Assets/Users/Suda/DividedPrefab/Pri_cells_gasStation.prefab.meta
- Assets/Users/Suda/DividedPrefab/enemyBillSub1_dest.prefab
- Assets/Users/Yamamoto/Animation/BlastIntro.meta
- Assets/Users/Yamamoto/Animation/BlastIntro/BlastButton.anim
- Assets/Users/Yamamoto/Animation/BlastIntro/BlastButton.anim.meta
- Assets/Users/Yamamoto/Animation/BlastIntro/Ezout.anim
- Assets/Users/Yamamoto/Animation/BlastIntro/Ezout.anim.meta
- Assets/Users/Yamamoto/Animation/BlastIntro/MobileUISet.controller
- Assets/Users/Yamamoto/Animation/BlastIntro/MobileUISet.controller.meta
- Assets/Users/Yamamoto/ChechScene_Y.unity
- Assets/Users/Yamamoto/Object/Enemy/Tank/ReTank.prefab
- Assets/Users/Yamamoto/Scripts/Enemy/Enemy_Y.cs
- Assets/Users/Yamamoto/Scripts/Object/GasStation_Y.cs
- Assets/Users/Yamamoto/Scripts/Object/GasStation_Y.cs.meta
- Assets/Users/Yamamoto/Scripts/Object/ObjectBreak_Y.cs
- Assets/Users/Yamamoto/Scripts/Video/BlastIntroduction_Y.cs
> 01-02mov動画の仕様変更
